[package]
name = "NFTMarketplace"
version = "1.0.0"
authors = ["Taiwo Triumphant"]
upgrade_policy="compatible"


[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
AptosStdlib = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "movement" }
AptosTokenObjects = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "movement" }


[addresses]
marketplace = "0x2a79f87aa5ee0e7ff1560dc330c7cad75cdbfad472a86cac461456f76e5a446c"